[package]
name = "folder_icon"
version = "2024.10.2"
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7.2", features = ["gettext-system"] }
image = {version = "0.25.2"}
gio = "0.20.4"
librsvg = "2.59.1"
cairo-rs = "0.20.1"
async-channel = {version = "2.3.1"}
resvg = {version = "0.44.0"}
usvg = "0.44.0"
log = "0.4.22"
pretty_env_logger = "0.5"
ashpd = "0.9.2"
rand = "0.8.5"



[dependencies.gtk]
package = "gtk4"
version = "0.9.2"
features = ["v4_10"]

[dependencies.adw]
package = "libadwaita"
version = "0.7"
features = ["v1_6"]
